function Script () {
    game.showLongText("Lisa: *yawn* If you're borrowing a book, please register it in the log. The restricted section is currently not lending any books...", DialogLayout.Bottom)
    game.showLongText("Lisa: Oh? It's you, little cutie.", DialogLayout.Bottom)
    game.showLongText("Lisa: It's so good to see you! More refreshing than a strong cup of tea in the afternoon.", DialogLayout.Bottom)
    game.showLongText("Y/N: Clearly you're meant to be working, but you don't seem to have your heart in it at all...", DialogLayout.Bottom)
    game.showLongText("Lisa: I mean, other than Jean, who really works that earnestly anyways?", DialogLayout.Bottom)
    game.showLongText("Y/N: Others work hard too!", DialogLayout.Bottom)
    game.splash("I do feel sorry for Jean always working so hard...")
    game.showLongText("Lisa: So did you have something you needed?...Or did you just come to see me?", DialogLayout.Bottom)
    game.showLongText("Y/N: I just wanted to see you!", DialogLayout.Bottom)
    game.showLongText("Lisa: Ooh, a smooth talker. Not what I was expecting.", DialogLayout.Bottom)
    game.showLongText("Y/N: So Miss Librarian, got any books to recommend?", DialogLayout.Bottom)
    game.showLongText("Lisa: Hmm... Recommended books... Sadly, everything I'd personally recommend is all in the restricted section, which we're not currently lending out.", DialogLayout.Bottom)
    game.showLongText("...(What's with her ominous tone?)", DialogLayout.Bottom)
    game.showLongText("Lisa: Oh, right. Would you be interested in checking out the Teyvat Travel Guide?", DialogLayout.Bottom)
    game.showLongText("Lisa: I think it would be quite helpful for you as travelers here.", DialogLayout.Bottom)
    game.showLongText("Y/N: Ooh! Sounds like it could be helpful! Do you think we could take a peek?!", DialogLayout.Bottom)
    game.showLongText("Lisa: I suppose I can try to find you a copy from the list...", DialogLayout.Bottom)
    game.showLongText("(Isn't that Lisa's job? What does she mean \"I suppose\"...?)", DialogLayout.Bottom)
    game.showLongText("Lisa: Oh dear... That's unfortunate. Our copy is currently being borrowed. That said, it is now overdue...", DialogLayout.Bottom)
    game.showLongText("Lisa: Come to think of it, quite a few of our books are now overdue. I REALLY wish people would just return their books on time!", DialogLayout.Bottom)
    game.showLongText("Y/N: Whoa! Am I imagining things, or does the air in here suddenly feel a lot more... electrified!?", DialogLayout.Bottom)
    game.showLongText("Y/N: It's giving me goosebumps!", DialogLayout.Bottom)
    game.showLongText("Lisa: Ugh... such a pain. I'm going out to bring those unreturned books back. If you'd rather get your hands on that copy of the Teyvat Travel Guide sooner, you'd better come with me.", DialogLayout.Bottom)
    game.showLongText("Y/N: Oh, ah, yes... YES!", DialogLayout.Bottom)
    game.showLongText("Lisa: You really are such a considerate cutie. Let's see, first we can go to the souvenir shop. It's called \"With Wind Comes Glory.\" So let's meet there shortly.", DialogLayout.Bottom)
    SCRIPT2()
}
function SCRIPT2 () {
    game.showLongText("(At With Wind Comes Glory)  Lisa: Y/N, you're here! Let's begin, shall we?", DialogLayout.Bottom)
    game.showLongText("Y/N: Marjorie, regarding the book you borrowed–", DialogLayout.Bottom)
    game.showLongText("Lisa: Hello Marjorie, any exciting new items in stock?  ", DialogLayout.Bottom)
    game.showLongText("Lisa: Why so surprised? Today is such a special day, it's only natural that I'd want a souvenir to remember it by.", DialogLayout.Bottom)
    game.showLongText("(Today is just an ordinary day...)", DialogLayout.Bottom)
    game.showLongText("Lisa: So it is... In that case, I declare this the \"Day of\"... the \"Day of My Life I Wish I Could Get Back Because I Spent My First Ever Outing With Traveler Taking Them on an Annoying Errand.\"", DialogLayout.Bottom)
    game.showLongText("Y/N: Don't you think that's a bit long?", DialogLayout.Bottom)
    game.showLongText("Marjorie: Haha... Well, if it's a souvenir you're after, you're in the right place. I'm sure you'll find something that strikes your fancy, Lisa.", DialogLayout.Bottom)
    game.showLongText("Marjorie: Or could let your new friend pick something out for you... make it more of an occasion?", DialogLayout.Bottom)
    game.showLongText("Y/N: I'll pick.", DialogLayout.Bottom)
    game.showLongText("Marjorie: Take a look around, there's sure to be something she'll love. (Choose a gift for Lisa.)", DialogLayout.Bottom)
    game.showLongText("Ragged Old Scroll  Marjorie: This is a historical relic retrieved from some ruins by one of the Adventurers' Guild.  Marjorie: Sure, there's a bit of wear and tear, but this thing in the painting must be well over a thousand years old... though it doesn't make much sense to me.  Lisa: My goodness... This is one of the three lost scrolls that make up the \"Northern Border Wind Investigation\"... What is it doing here!?", DialogLayout.Bottom)
    game.showLongText("Majorie: You sure you wanna pick the scroll? Can't change again once you've made your mind up!", DialogLayout.Bottom)
    game.showLongText("Lisa: My my, you clearly know a treasure when you see it. This is a work of unparalleled significance for the research of ancient people's understanding of the elements. I will gladly accept it.", DialogLayout.Bottom)
    game.showLongText("Lisa: Goodness, is that the time? Marjorie, one last thing – about \"The Legend of Vennessa\"–", DialogLayout.Bottom)
    game.showLongText("Marjorie: Oh, so you're a fan of the gallant Lady Vennessa too? Why didn't you say so? I have all sorts of items I could recommend...", DialogLayout.Bottom)
    game.showLongText("Marjorie: For example, this lion's tooth pendant with Vennessa's name carved into it. It was once a medal awarded to a knight by the great lady herself!", DialogLayout.Bottom)
    game.showLongText("Lisa: ...", DialogLayout.Bottom)
    game.showLongText("Y/N: The library book you borrowed.", DialogLayout.Bottom)
    game.showLongText("Marjorie: Oh my goodness! I do apologize, I got so excited when you mentioned Vennessa. I didn't know that book was overdue. Even though I take it with me everywhere...I can't believe I didn't put two and two together as soon as I saw you here, haha... Here you go.", DialogLayout.Bottom)
    game.showLongText("Lisa: *sigh* Well, since you look up to Lady Vennessa so very much... Please be more punctual next time.", DialogLayout.Bottom)
    game.showLongText("Marjorie: Yes, Lisa. I will be, Lisa.", DialogLayout.Bottom)
    game.showLongText("Lisa: Let's go and find the next overdue book.", DialogLayout.Bottom)
    script3()
}
function script3 () {
    game.showLongText("(At Good Hunter)  Sara: Welcome to Good Hunter. Table for two?", DialogLayout.Bottom)
    game.showLongText("Y/N: Yes.", DialogLayout.Bottom)
    game.showLongText("Sara: Please sit wherever you like and call me over once you're ready to order.", DialogLayout.Bottom)
    game.showLongText("Y/N: So we're gonna eat first and bring up the book situation later?", DialogLayout.Bottom)
    game.showLongText("Lisa: Why, of course. The stress of work really takes the pleasure out of eating, don't you think?", DialogLayout.Bottom)
    game.showLongText("Y/N: What does Lisa like to eat?", DialogLayout.Bottom)
    game.showLongText("Sara: She's been here a few times with Master Jean for afternoon tea before. I think she normally orders something vegetarian.", DialogLayout.Bottom)
    game.showLongText("Sara: A lady tends to eat cautiously on account of her physique, after all! On that note, I should probably be watching my own diet a little more...", DialogLayout.Bottom)
    game.showLongText("Lisa: *yawn*... Why don't you order us something, Traveler? I'm ever so curious to know what your tastes are. (Pick a dish that Lisa will like)", DialogLayout.Bottom)
    game.showLongText("Invigorating Pizza", DialogLayout.Bottom)
    game.showLongText("Lisa: *gasp* It's like you read my mind... Do you have some magical powers you're not telling me about, Outlander?", DialogLayout.Bottom)
    game.showLongText("Lisa: Wow, Jean must have given you some pointers? Such extraordinary lengths to prepare for a delicious meal... I'd almost say that's cheating.", DialogLayout.Bottom)
    game.showLongText("Lisa: I didn't know you and Jean got on so well. She used to make this for me once in a while too.", DialogLayout.Bottom)
    game.showLongText("Lisa: As it happens, this is exactly what I was craving - the perfect treat after a tiresome day of work. You've outdone yourself.", DialogLayout.Bottom)
    game.showLongText("Y/N: Oof... I'm so full...", DialogLayout.Bottom)
    game.showLongText("Lisa: Time is getting on. I suppose I should carry on with this ghastly thing called work.", DialogLayout.Bottom)
    game.showLongText("Lisa: Onto our next stop then, Traveler.", DialogLayout.Bottom)
    script4()
}
function script4 () {
    game.showLongText("Lisa: This is our final call for the day.", DialogLayout.Bottom)
    game.showLongText("Donna: Welcome...! Uh... c–couples are our specialty! Let me know what you'd like and I'll wrap them up nicely for you.", DialogLayout.Bottom)
    game.showLongText("Lisa: Ah yes... Now which book was it that has the line, \"a date without flowers is a date without romance\"?", DialogLayout.Bottom)
    game.showLongText("Would you by any chance care for some flowers, milady?", DialogLayout.Bottom)
    game.showLongText("Lisa: Why, it just so happens that I would, my kindest cutie.", DialogLayout.Bottom)
    game.showLongText("Donna: Some flowers for Miss Lisa? What would you like? (Pick a kind that Lisa will like)", DialogLayout.Bottom)
    game.showLongText("Dandelion", DialogLayout.Bottom)
    game.showLongText("Donna: Dandelions are one of our classics, and a personal favorite of Miss Flora, the shop owner.", DialogLayout.Bottom)
}
let lisa = sprites.create(img`
    ......bbcccccceecccccccccecccccccccffffccb11dbdd1ddbbcfcbbbccbbbbbbbbbbbbbbbbcff
    ........cfccccccccccccbccfcccccccfffcfffffcbbbd1111cffcbdbbcfcfbbbbbbbbbbbbbbbcf
    .......bffffffccccccccdbccccccccccfffcfffffccbdd111dcbdddbbcffcbbbbbbbbbbbbbbbbc
    .......cffffffccccccccbccccccccffffffffffccccddd111dbdddddbbcfcbbbbbbbbbbbbbbbbb
    ......bffffffffcccaaccccccccffffffcccccccccccd1dddddddddddbbbbbbbbbbbbbbbbbbbbbb
    ......cfffffffffccabccccccfffffffffcccfcfcffc11ddcbddddddddbbbbbbbbdbbbbbbbbbbbc
    .....bcffffffffffccbbccccffffffffffcbccccfccd11ddbdddddddddddbbbdddddbbbbbbbbbbf
    .....ccfffffffffffccbccfffffffffcfffcccfcbddd11bbddddddddddddddbbbbbddbbbbbbbbcf
    ....bcccffffffccffccbcfffffffffffffcffccbdddb1dbddddddddddddddbbbbbbbdbd9bbbbbff
    ...bcccccffffccccccccfffffffcffffffcfcccddd11dbdddddddddddddddbbccbbbbbbbbbbbcff
    ...ccccaccffcbccc8cccccffffffffffccbbccd1bd11ddddddddddddddddbbcffbbbbbbbbbbffff
    ..bccccbbcffcddbccccaaacfffffffcbd3dddd1dcb11ddddddddddddddddbbcfffcbdddddcfffff
    .bccccbdddcfcbdddccaaaaafffffcb11dd11d11dbbddbbbdddddddddddddbbcfccbbbbdddbfffff
    .ccccbddddbcfccbddcaaa8affffbd11dbd11dbbbbcccccccbdddddddddddbbccbbbbbbbbdbcffff
    bccccbdddbbcccaccbccaa8cfffcbddbbbd111bffffcccccccbdddddddddddbbbbbbbddbbbdbffff
    cccccbdbbbcccaaabacc8a8cffffccccccb1d1bffffccccccccbdddddddddddbbbbddddbbbdbcfff
    ccccccccccccba8aa8aaaa8ccfffcccccccccccfffcceeccccccbddddddddddddddddddbbbbdcfff
    bbbccccccccccc8aa8ca88accfffcccccccccffffceeeeeeecccccbdddddbbbbbdddbbdbbbbdbfff
    ......cccccccccaacc88acacffccccccccffffffebbbbbbeeccccccddbbbbbbddddbbbbbbbdbfff
    ......cccffcfccbaaaaa8aaffccccccccffffffebbbbbbbbbeccccccbbbccbdbddddbbbbdbbbfff
    .....cfffccccccabbaaaaacffccccccfffffffcbbbbbbbbbbecccccccbcffcdbddddbbbbbbbbffc
    b.bcffffcccccccaaaaaaccffcccccffffffffcbbbbbdbbbdbbeccccccccffcddbbbdbbbbbbbcffb
    bbcfffffccccccccaaaccffcccccfffffffffcbbbbedddbbddbeceeccccccccbddbbbbbbdbbcffc.
    cfcccfffccccccccaaacfffffffffffffffccbdbbebbbbbbbbbecebeccccbdddddddddbbccffff..
    ffcbcffffcfccccccccfffffffffffffffcebbbbebbbbbbbbbbeceebeccccbdbdbbccccffffffc..
    fffffffffffffffccccfffffffffffffcceebbbbbbbbbbbbbbbeeeebbecccbdddbcffffffffffb..
    fffffffffffffffcccffffffffffffccccebbbbebbbbbebbbbbeeeebbbeccbddddcfffffffffc...
    ffffffffffffffffcffffccffffccccecceeeeebdbbbbebebbbeeeebbbecccbbddcfffffffcc....
    .ccccccfffffffffffffcccffffcccceccceebbddbbbbebebbbeeeebbbbeccbbbdcffffccccb....
    ......bfffffffffffcccffffffceccecccebbbddbbbeeeebbbeeeeebbbbeccbddccccccccc.....
    .......cffffffffffccccfffffceeeecebbbdd11bbbeeeebbeebbeebbbeeccbddccccccc.......
    ........fffffffcffcccfffffcebbbeebbbbddddbbbeeebbbeeb3eebebeeeccbbccccccc.......
    ........cfffffffffffffffffcebbbbcbeeccceeebdeeebbeebddbebbbeecccccccccc.........
    ........cffffffffffffffffccbbbebcffbcfffeeddeebbbeebbbbebbebcccbccccccc.........
    ......bcffffffffffffffffccebbbebefecccccbebdbebbeebdddbebbeecceccccccc..........
    ......cffcccffffffffffffccbbbbeebebb777cdbddebbebddddddeebecccccccccb...........
    .....bfffcbcffffffffffceccbbbbbebeddd77d1ddbbbebddbeebdeebbccccccccb............
    ....bffffcbcfffffffffcbecebbbbbebedddddd1ddebbddddbfcfeeebbccccccb..............
    ....ffffffccfffffffffbbecebbbbbeeebdddddddbbdddd1beebeeeebbcccccb...............
    .bcfffffffffffffffffcbbeceebbbbbeebddddddd1111111dbbbbeeeebecbb.................
    dcfffffffffffffffffccbbeccebbbbbeeedddddd11111111dddddeceebeb...................
    cffffffffffffffffcccccbeceebbbebbeceddddd111111d1dddddcceebeb...................
    ffffffffffffffcccccccccbccebbbbebbbeddddd111111d11ddddcbbebbb...................
    ffffffffffffcbbbccccccccfccebbbbeeebddddd11111111dddddbddeeeb................dd1
    fffffffffccbbbbcccccccccccceebbbbeecbd1111111111111ddddddeebb..............ddd11
    fffffffcbbbbbbbccccccccccccceebebbed111111111111111ddbdddeebb.............1dd11d
    fffffcbbbbdbddbccccccccccccceeeeebbbd1111dddd1d1111ddbdddcbbb.............dd1ddd
    ffffcbbbbdbdddccccceccccceecceeeeebbbbd111ddddddd111bcbbbbbbd.............11dddd
    fccbbbbbbdbdddccccbbbecceeecefeeeeeebbebbbd111111dddbdbbbbbd............b1dddddb
    cbbbbbbbdddddbccbcceeeccceeeeeeeeeeeeeeebb1111111dcecbbbbbb........bbb.b1ddddddb
    bbbbbbbbcddddbccbbbbbbbbbbbeeeebbbbbbbdd1111111111bbbbbbbb...bbcccccccb1ddddddb.
    bbbbbccccbddddcccbbbbbbbbbdddbbeebdddd11111111111dbdbbbbbb...ccccccccd1dddddbb..
    ccccccccccbdddccccbbbbbbbbbbbbbbeeedddd111111111dbddddbcb...bccccccbdddbbbbb....
    cccccccccccdddbcbbceebbbbbbbbbbbeeeedbbdd111111dbd1ddbbd....ccccccbddbccc.......
    ccccccccccccbbbccbbbbbbbbbbdbbbbbbeeebeeebdd11dbbd111dd....ccccfcbbccffffb......
    cccccccccccccccccebbbbbbbbbbbbbbbbbebeeeeeebbbbeeb........ccccfcbcffcfffccd.....
    cccccccccccccccccccbbbbbbddbbbbbbbbbeeeeeeebbeeeeecbbd...bccfeeccfffccfffcc.....
    cccccccccccccccccccbbbbbddbbbbbbbeebcfeeeeebbeceeeecc.....beeefffffccccfffc.....
    ccccccccccccccccccccbbbbbbbeeeeebbeecfeeeecccbbcceeccc...bbeecfffffccccffffc....
    ..ccccccccccccccccccccebbeeeecceeeeecfcecfccbbbcceeccccbebefccfffffcfccffffccd..
    ..............ccccccccccccccccfceeecfffcffcbccbbcccccccccfffffffffcccccccccccb..
    ..............cccccccccccccccfffeeecffffffcbbddddddcccccbfffffffffffffcccfffcc..
    .............ccccccccccccccfffffceecfffffcbd1111111dbccc.bbbbcfffffcffffffffffc.
    .............ccccccccccccccffffccccfffffcb1111111111dcec.....bfffffcccfffffffffc
    .............ccccccccccccffffffcccffffcbb111111111111bcc......bcffcccfffffffffff
    .............ccccccfccffffffffffccfffcbbd111111111111dcccb......cfccffffffffffff
    .............bccccffffffffffcccccfffcbbd11111111111111ccbcc......bbbccffffffffff
    ............bbcccfffffffffcccfcffffcbbbd11111111111111dbaaacb........bffffffffff
    .............bbccffffffccccccccfffcbbbbd111111111111111cbcacc........bcfffffffff
    ............bbbccffffccccccccccfcfcbbbbb111111111111111bbcccfc........cfffffffff
    ...........bbbcccccccccccccccccccfcccbbbd11111111111111bccccffcb......cccfffffff
    ...........bbccccccccccccccccccccccccccbbd1111111111111dccccffc......bccffffffff
    ...........ccccccccccccccccccccccccccccccbbd11111111111dccfffcb......bcccffffffc
    ...........cccccccccbccccccccccccccccccccabbbbbbdddddddcccccccc.....dcccbcfcfff.
    ...........ccccccccbbbccccccccccbccccccccccaabbbbbbbbbcccccfcccb....bcbbccccccc.
    ...........cccccccbddbbccccccccbbbccccccccccccaaaabbbccccccccccb...dcccbcfccccc.
    ...........ccccccbd1dbcccccccccbddccccccccccaaaaaaabaccabcccccbbb..bbcbbfffcccf.
    ..........cccccccbd1dbccccccccbddddcccccccccaaabaaaaaaabbbcccccbbbbcbcccccccccf.
    ..........cccc8cccddbcccccccccbddddbccccccccaaaaaabbbbbbbbccccccbcbbbccccccfccc.
    .........cc8888cccbbbbccccccccdddd1dccccccccaaaaabbbbbbbbcccccccccccbbbbcccffcc.
    .........c8888ccbcbbcbcccccccbdddd1dccccccccababbbbbbbbbbbcbccccbccceebbccccccc.
    .........888c8ccbcbbbbcccccccbdddd11cccccccccbbbbbbbbbbbbbccbcccbbbccccccccbccc.
    ........c88888ccbbcbbccccccccbdddd11bccccccccbbbbbbbbbbbbbcccccbccccebbcccbdbcc.
    .......bc888ccbbbccbbccccccccbeeebbdbccccccccbbbbabbbbbbbbbbbbccbcbbddddbdddbc..
    ......bc888ccbbbbbcbbccccccccccbbbbbcccccccccbbbbbbbbbbbbbbbbbcbbcbdddddddddcb..
    .....dc888cbcbbbebbdbccccccccccccbbbccccccccbbbbbbbbbbbbbbbbbcbbbcbdddddddddc...
    ...d.c88cccccbbcbcbdbbccccccccfffcccccccccccbbbbbbbbbbbbbbbbcbbbccddddddddddc...
    ....b88ccccccccbbcbccbcccccccffffccfccccccccbbbbbbbbbddbbbbbbbbbcbdddddddddbc...
    ...bccccc88cccbdbbcccbcccccccffffccfccccccccbbbbbbbbbdddbbdbbbbbcddddddddddbc...
    ..dccbcc8cccbbddcbccccbcccccfffffccfccccccccbbbbbbbdbddbbd1dbbbccbdddddddddbb...
    .dccabc8ccbbcbdbcbccccbcccccfffffcfccccccccbbbbbdcddbbbbdddbbbbbbcbddddddddbb...
    .c8cbbcccbbbdbdbbbccccbcccccfffffffcccffcbccbbbddbd1dbbddbbbbbbbbbcbbddddddc....
    b8cbddbbbbbd.bdcbbccccbccccffffffffccffccbbcbbbddbd11ddbbbbbbdbbbbbccebddddc....
    ccbddddbccd..bbbbbccccbbcccfffffffccccfccbbbbbdddb11dddbbbbbbdddbbbccbddddbc....
    cabbbbbccb...bcbcbccccbbccffffffffccccfccbbbbdbbb1d11dbbbbbbbcbbbcccbddddbbc....
    abccbbcbb....dcbcdccccbbccffffffffcccfffcccbbddddd11bbbdbbbbcbbcbbbdddddbbbb....
    ccabccabd....dbccdbccbdcccffffffffffffcffccbbbbbbbbbbd1111bbcbdbbddddbbbbbc.....
    cbbcccbd.....bbccbdbbddcccfffffffffcccccffffccbbbbbdd11111bbcddbbddddbbbbbc.....
    bccacbb......bbcccbdddbcccffffffffccccccffffffbbd11bd1111ddcbdddbbddbbbbbbc.....
    ccaabb......dbcccaccbdccccffffffffcccccccffffcbd11bbbbbdddbedddd3bddbbbbbbc.....
    aaabbb......bbcccbccbdcccccfffffffccccccccfffbdddbbdddbbbbbddd1ddbbdbbbbbbb.....
    aacbb......dbccccbcccbcccccfffffffcccccccccfcbbbccdddddddddddd1ddbbdbbbbbbb.....
    acbb.......bbccccbcccaccccccfffffccccccccccfffffffbddd111ddddd11dbbddbbbbcb.....
    ccb........bbccccbccccccccccfffffccccccccccfffffffeddd1111111111dbbddbbbbc......
    bbb.......dbcccccbbcccccccccfffffccccccccccfffffffcddd11111111111dbddbbbbc......
    .b........bbcccccdbcccccccccffffffccccccccccfffffccedd11111111111d3dddbbbb......
    b.........bdcccccddccccccfcccfffffcccccccccccfffcbbedd11111111111d3dddbbc.......
    b........dbdccccbbdbcccccfcccfffffcccccccccccfffcbbeed11111111111ddddbbbc.......
    .........bdddbcbdbbbcccccfcccfffffccccccccccccfffcbbbbd1111111111ddddbbc........
    .........bdbbdddbcadcccccccfccfffffccccccccccccfcbccceb1111111111ddddbc.........
    ........dbbaabdbaccbbccccccfccfffffcccccccccccccbcfccccd111111111ddddb..........
    ........dbaaabdaaccbbcccccccfccffffccccccccccccbbcfccccbd1111111ddddb...........
    ........bbaaabbaaacbbccccccccccffffcccccccccccddbffcccced1111111dddd............
    `, SpriteKind.Player)
let yn = sprites.create(img`
    .....................eeeeeeeee11111111111111....................
    ...................eeeeeeeeeeee1111111111111111.................
    ..................eeeeeeeeeeeeee1111111111111111................
    ................eeeeeeeeeeeeeeeeeeeeeee1111111111...............
    ...............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeee1111e.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee11e1...........
    .............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee11e...........
    ............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..........
    ...........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.........
    ..........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee........
    ..........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.......
    ..........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.......
    .........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.......
    ..........e1eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......
    .........eeeeeeeeeeee1eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......
    ........eeeeeeeeeee111eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......
    ........eeeee11ee11111eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......
    ........eeeee1eee11e11eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.....
    ........eeeeeeee11111eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.....
    .......eeeeeeeeeee1e1ee1111ee1eeeeeeeeeeeeeeeeeeeeeeeeeeeee.....
    .......eeeeeeeeeee1e1ee1111ee111eeeeeeeeeeeeeeeeeeeeeeeeeee.....
    .......eeeeeeeeeeeee1ee1111ee1111eeeeee1eeeeeeeeeeeeeeeeeee.....
    ........eeeeeeeeeeeeee11111e11111eeeeee1eeeeeeeeeeeeeeeeeee.....
    ........eeeeeeeeeeeeeeeeeeeeeeeeeee111e1eeeeeeeeeeeeeeeeeee.....
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee....
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee....
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebeeeeeeeee....
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee....
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbeebbeeeee.....
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbebbbeeee......
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbeebbeeeee......
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebeebbebdbeeee.......
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbddbee.........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbeeebdd1dbee.........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbd1d1ddbb..........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebd1dd11111dd11.........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebd1111111111111.........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeed111111111111111........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeb1111111111111111........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeb1111111111111111........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebb111111111111111.........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedb11111111111111..........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedd11111111111111..........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeed1111111ddddd11...........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeee11111111111111............
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeee11111111111111............
    .......eeeeeeeeeeeeeeeeeeeeeeeeeefeeee11111111111111............
    .......eeeeeeeeefeeeeeeeeeefeeeeefceee1111111111111.............
    .......eeeeeeeeefeeeeeeeeeefeeeeffceee1111111111111.............
    .......eefeeeeeefeeeeeeeeeefceeeffceeed11111111111..............
    .......ecfceeeeefccfeeeeecefceecffceceddd111111111..............
    ......eecffeeeeefccffeeeeefffeefffeeeeeebdd1111111..............
    ......ecfffeeeeefccffeceeefffeefffeeceeeecebdd111...............
    ......ecffeeeeeffccfeceeeffffeeffeeeceeeecccebb.................
    ......ecffeeeeffccffeeeeefffeeeffeeeceeeccccccc.................
    .....becfeeeeeffccffeeeeffffeeeffeeeceeeccccccc.................
    .....becfeeeefffcfffeeecffffeeefffeeccceeceeeec.................
    .....befeeeeffffffffeefcfffceeefffeeccceeceeeee.................
    ....beefeeeefffcfffeeefcffeeeeeffceecccececeeec.................
    ....beefeeeffffcfffeefcffeeeeeeffceeccccceceeec.................
    ...bbecfeeefffecffeeefcfeeeeeeeffeeeeccececebeb.................
    ...bbecfeefffeeffeeefcfeeeeeeeeffceeecccceccbbb.................
    ...becfeefffeecfeeeffceeebeeeeeefeeeeecccbcbdbb.................
    ..bbeceefeeeecfeeeffffeebbeeeeeefeeeebbccccbdbb.................
    bbbeceefffcccfeecffffeeedbeeeeebfeeeebdbccfcbbb.................
    bbeccefffccceecffffeeeebdeeeeeebeeeeed1dbcfffcc.................
    beccfffcccceefffffeceebddeeeeeebeeeeed11dbcccffcb...............
    ecfffcffffffffffcecceebdbeeeeeedeeeeeb111dcccccccb..............
    fffffcccfccffffceccebbdbeeeeeeedeeeeebd111bccccccbb.............
    ffffffffcceecffccbbbbddbeeeeeebdeeeeebd111dbcccccbbb............
    cffffcfffceeecffcbbbbdbeeeeeeebdeeeeebd1111dcccccbbbb...........
    fffccccccffeeeccfcbbdbbeeeeeeed1eeeeebdd1111bcccccbbb...........
    fcccccccccccceeeccbbbeeeeeeeebbdbeeeebdd1111dcccccbbbb..........
    cccccccccccccceeeeeeeeeeeeeeebbdbeeeebdd11111bccccbbbb..........
    cccccccccccccccceeeeeeeeeeeebdbdbeeeebddd1111dccccbbbb..........
    ccccccccccccccccceeeeeeeeeeedbbddeeeedddd11111bccccbbbb.........
    cccccccccccccccccccceeccceeddbdddeeeedd1d11111dbcccbbbb.........
    ccccccccccccccccccccfffccbd1dbdddeeeebd1d111111bcccbbbbb........
    ccccccccccccccccccccfffcd111dddddeeeedddd111111dbccbbbbb.b......
    cccccccccccccccccccccffcb11ddddddeeeedd1dd111111bcccbbbb.b......
    ccccccccccccccccccccccfccddddddddeeeedd1dd111111bcccbbbb.b......
    cccccccccccccccccccccccfccbd1ddddeeeedd11bbd1111bcccbbbb.b......
    cccccccccccccccccccccccccccd1ddddeeeedd1dbbbdddbbcccbbbbbb......
    ccccccccccccccccccccccccccccdddddeeeedd1dbbbbbbbbbccbbbbbb......
    `, SpriteKind.Player)
controller.moveSprite(yn)
yn.setPosition(38, 43)
lisa.setPosition(122, 57)
Script()
