function Script () {
    game.showLongText("Lisa: *yawn* If you're borrowing a book, please register it in the log. The restricted section is currently not lending any books...", DialogLayout.Bottom)
    game.showLongText("Lisa: Oh? It's you, little cutie.", DialogLayout.Bottom)
    game.showLongText("Lisa: It's so good to see you! More refreshing than a strong cup of tea in the afternoon.", DialogLayout.Bottom)
    game.showLongText("Y/N: Clearly you're meant to be working, but you don't seem to have your heart in it at all...", DialogLayout.Bottom)
    game.showLongText("Lisa: I mean, other than Jean, who really works that earnestly anyways?", DialogLayout.Bottom)
    game.showLongText("Y/N: Others work hard too!", DialogLayout.Bottom)
    game.splash("I do feel sorry for Jean always working so hard...", "")
    game.showLongText("Lisa: So did you have something you needed?...Or did you just come to see me?", DialogLayout.Bottom)
    game.showLongText("I just wanted to see you!", DialogLayout.Bottom)
    game.showLongText("Lisa: Ooh, a smooth talker. Not what I was expecting.", DialogLayout.Bottom)
    game.showLongText("So Miss Librarian, got any books to recommend?", DialogLayout.Bottom)
    game.showLongText("Lisa: Hmm... Recommended books... Sadly, everything I'd personally recommend is all in the restricted section, which we're not currently lending out.", DialogLayout.Bottom)
    game.showLongText("...(What's with her ominous tone?)", DialogLayout.Bottom)
    game.showLongText("Lisa: Oh, right. Would you be interested in checking out the Teyvat Travel Guide?", DialogLayout.Bottom)
    game.showLongText("Lisa: I think it would be quite helpful for you as travelers here.", DialogLayout.Bottom)
    game.showLongText("Ooh! Sounds like it could be helpful! Do you think we could take a peek?!", DialogLayout.Bottom)
    game.showLongText("Lisa: I suppose I can try to find you a copy from the list...", DialogLayout.Bottom)
    game.showLongText("(Isn't that Lisa's job? What does she mean \"I suppose\"...?)", DialogLayout.Bottom)
    game.showLongText("Lisa: Oh dear... That's unfortunate. Our copy is currently being borrowed. That said, it is now overdue...", DialogLayout.Bottom)
    game.showLongText("Lisa: Come to think of it, quite a few of our books are now overdue. I REALLY wish people would just return their books on time!", DialogLayout.Bottom)
    game.showLongText("Whoa! Am I imagining things, or does the air in here suddenly feel a lot more... electrified!?", DialogLayout.Bottom)
    game.showLongText("It's giving me goosebumps!", DialogLayout.Bottom)
    game.showLongText("Lisa: Ugh... such a pain. I'm going out to bring those unreturned books back. If you'd rather get your hands on that copy of the Teyvat Travel Guide sooner, you'd better come with me.", DialogLayout.Bottom)
    game.showLongText("Oh, ah, yes... YES!", DialogLayout.Bottom)
    game.showLongText("Lisa: You really are such a considerate cutie. Let's see, first we can go to the souvenir shop. It's called \"With Wind Comes Glory.\" So let's meet there shortly.", DialogLayout.Bottom)
    SCRIPT2()
}
function SCRIPT2 () {
    game.showLongText("(At With Wind Comes Glory)  Lisa: Y/N, you're here! Let's begin, shall we?", DialogLayout.Bottom)
    game.showLongText("Y/n: Marjorie, regarding the book you borrowed–", DialogLayout.Bottom)
    game.showLongText("Lisa: Hello Marjorie, any exciting new items in stock?  ", DialogLayout.Bottom)
    game.showLongText("Lisa: Why so surprised? Today is such a special day, it's only natural that I'd want a souvenir to remember it by.", DialogLayout.Bottom)
    game.showLongText("(Today is just an ordinary day...)", DialogLayout.Bottom)
    game.showLongText("Lisa: So it is... In that case, I declare this the \"Day of\"... the \"Day of My Life I Wish I Could Get Back Because I Spent My First Ever Outing With Traveler Taking Them on an Annoying Errand.\"", DialogLayout.Bottom)
    game.showLongText("Don't you think that's a bit long?", DialogLayout.Bottom)
    game.showLongText("Marjorie: Haha... Well, if it's a souvenir you're after, you're in the right place. I'm sure you'll find something that strikes your fancy, Lisa.", DialogLayout.Bottom)
    game.showLongText("Marjorie: Or could let your new friend pick something out for you... make it more of an occasion?", DialogLayout.Bottom)
    game.showLongText("I'll pick.", DialogLayout.Bottom)
    game.showLongText("Marjorie: Take a look around, there's sure to be something she'll love. (Choose a gift for Lisa.)", DialogLayout.Bottom)
    game.showLongText("Ragged Old Scroll  Marjorie: This is a historical relic retrieved from some ruins by one of the Adventurers' Guild.  Marjorie: Sure, there's a bit of wear and tear, but this thing in the painting must be well over a thousand years old... though it doesn't make much sense to me.  Lisa: My goodness... This is one of the three lost scrolls that make up the \"Northern Border Wind Investigation\"... What is it doing here!?", DialogLayout.Bottom)
    // option here
    game.showLongText("System: You sure you wanna pick the scroll? Can't change again once you've made your mind up!", DialogLayout.Bottom)
    game.showLongText("Lisa: My my, you clearly know a treasure when you see it. This is a work of unparalleled significance for the research of ancient people's understanding of the elements. I will gladly accept it.", DialogLayout.Bottom)
    game.showLongText("Lisa: Goodness, is that the time? Marjorie, one last thing – about \"The Legend of Vennessa\"–", DialogLayout.Bottom)
    game.showLongText("Marjorie: Oh, so you're a fan of the gallant Lady Vennessa too? Why didn't you say so? I have all sorts of items I could recommend...", DialogLayout.Bottom)
    game.showLongText("Marjorie: For example, this lion's tooth pendant with Vennessa's name carved into it. It was once a medal awarded to a knight by the great lady herself!", DialogLayout.Bottom)
    game.showLongText("Lisa: ...", DialogLayout.Bottom)
    game.showLongText("The library book you borrowed.", DialogLayout.Bottom)
    game.showLongText("Marjorie: Oh my goodness! I do apologize, I got so excited when you mentioned Vennessa. I didn't know that book was overdue. Even though I take it with me everywhere...I can't believe I didn't put two and two together as soon as I saw you here, haha... Here you go.", DialogLayout.Bottom)
    game.showLongText("Lisa: *sigh* Well, since you look up to Lady Vennessa so very much... Please be more punctual next time.", DialogLayout.Bottom)
    game.showLongText("Marjorie: Yes, Lisa. I will be, Lisa.", DialogLayout.Bottom)
    game.showLongText("Lisa: Let's go and find the next overdue book.", DialogLayout.Bottom)
    script3()
}
function script3 () {
    game.showLongText("(At Good Hunter)  Sara: Welcome to Good Hunter. Table for two?", DialogLayout.Bottom)
    game.showLongText("Yes.", DialogLayout.Bottom)
    game.showLongText("Please sit wherever you like and call me over once you're ready to order.", DialogLayout.Bottom)
    game.showLongText("So we're gonna eat first and bring up the book situation later?", DialogLayout.Bottom)
    game.showLongText("Lisa: Why, of course. The stress of work really takes the pleasure out of eating, don't you think?", DialogLayout.Bottom)
    game.showLongText("What does Lisa like to eat?", DialogLayout.Bottom)
    game.showLongText("She's been here a few times with Master Jean for afternoon tea before. I think she normally orders something vegetarian.", DialogLayout.Bottom)
    game.showLongText("A lady tends to eat cautiously on account of her physique, after all! On that note, I should probably be watching my own diet a little more...", DialogLayout.Bottom)
    game.showLongText("Lisa: *yawn*... Why don't you order us something, Traveler? I'm ever so curious to know what your tastes are. (Pick a dish that Lisa will like)", DialogLayout.Bottom)
    game.showLongText("Invigorating Pizza", DialogLayout.Bottom)
    game.showLongText("Lisa: *gasp* It's like you read my mind... Do you have some magical powers you're not telling me about, Outlander?", DialogLayout.Bottom)
    game.showLongText("Lisa: Wow, Jean must have given you some pointers? Such extraordinary lengths to prepare for a delicious meal... I'd almost say that's cheating.", DialogLayout.Bottom)
    game.showLongText("Lisa: I didn't know you and Jean got on so well. She used to make this for me once in a while too.", DialogLayout.Bottom)
    game.showLongText("As it happens, this is exactly what I was craving - the perfect treat after a tiresome day of work. You've outdone yourself.", DialogLayout.Bottom)
    game.showLongText("Oof... I'm so full...", DialogLayout.Bottom)
    game.showLongText("Lisa: Time is getting on. I suppose I should carry on with this ghastly thing called work.", DialogLayout.Bottom)
    game.showLongText("Lisa: Onto our next stop then, Traveler.", DialogLayout.Bottom)
    script4()
}
function script4 () {
    game.showLongText("Lisa: This is our final call for the day.", DialogLayout.Bottom)
    game.showLongText("Donna: Welcome...! Uh... c–couples are our specialty! Let me know what you'd like and I'll wrap them up nicely for you.", DialogLayout.Bottom)
    game.showLongText("Lisa: Ah yes... Now which book was it that has the line, \"a date without flowers is a date without romance\"?", DialogLayout.Bottom)
    game.showLongText("Would you by any chance care for some flowers, milady?", DialogLayout.Bottom)
    game.showLongText("Lisa: Why, it just so happens that I would, my kindest cutie.", DialogLayout.Bottom)
}
let lisa = sprites.create(img`
    ......bbcccccccccccccccccccccccccccffffccb11dbdd1ddbbcfcbbbccbbbbbbbbbbbbbbbbcff
    ........cfccccccccccccbccfcccccccfffcfffffcbbbd1111cffcbdbbcfcfbbbbbbbbbbbbbbbcf
    .......bffffffccccccccdbccccccccccfffcfffffccbdd111dcbdddbbcffcbbbbbbbbbbbbbbbbc
    .......cffffffccccccccbccccccccffffffffffccccddd111dbdddddbbcfcbbbbbbbbbbbbbbbbb
    ......bffffffffcccccccccccccffffffcccccccccccd1dddddddddddbbbbbbbbbbbbbbbbbbbbbb
    ......cfffffffffcccbccccccfffffffffcccfcfcffc11ddcbddddddddbbbbbbbbdbbbbbbbbbbbc
    .....bcffffffffffccbbccccffffffffffcbccccfccd11ddbdddddddddddbbbdddddbbbbbbbbbbf
    .....ccfffffffffffccbccfffffffffcfffcccfcbddd11bbddddddddddddddbbbbbddbbbbbbbbcf
    ....bcccffffffccffccbcfffffffffffffcffccbdddb1dbddddddddddddddbbbbbbbdbdbbbbbbff
    ...bcccccffffccccccccfffffffcffffffcfcccddd11dbdddddddddddddddbbccbbbbbbbbbbbcff
    ...cccccccffccccc8cccccffffffffffccbbccd1bd11ddddddddddddddddbbcffbbbbbbbbbbffff
    ..bccccbbcffccccccccaaacfffffffcbdddddd1dcb11ddddddddddddddddbbcfffcbdddddcfffff
    .bccccbbbbcfcccccccaaaaafffffcb11dd11d11dbbddbbbdddddddddddddbbcfccbbbbdddbfffff
    .ccccbbbbbbcfccbcccaaa8affffbd11dbd11dbbbbcccccccbdddddddddddbbccbbbbbbbbdbcffff
    bccccbbbbbbcccaccbccaa8cfffcbddbbbd111bffffcccccccbdddddddddddbbbbbbbddbbbdbffff
    cccccbbbbbcccaaabacc8a8cffffccccccb1d1bffffcffcccccbdddddddddddbbbbddddbbbdbcfff
    ccccccccccccba8aa8aaaa8ccfffcccccccccccfffffeefffcccbddddddddddddddddddbbbbdcfff
    bbbccccccccccc8aa8ca88accfffcccccccccfffffeeeeeeefccccbdddddbbbbbdddbbdbbbbdbfff
    ......cccccccccaacc88acacffccccccccffffffeeeeeeeeefcccccddbbbbbbddddbbbbbbbdbfff
    ......cccffcfccbaaaaa8aaffccccccccffffffeeeeeeeeeefccccccbbbccbdbddddbbbbdbbbfff
    .....cfffccccccabbaaaaacffccccccffffffffeeeeeeeeeefcccccccbcffcdbddddbbbbbbbbffc
    b.bcffffcccccccaaaaaaccffcccccfffffffffeeeeedeeedeefccccccccffcddbbbdbbbbbbbcffb
    bbffffffccccccccaaaccffcccccffffffffffeeeefdddeeddefcffccccccccbddbbbbbbdbbcffc.
    cfffffffccccccccaaacfffffffffffffffffedeefeeeeeeeeefcfbfccccbdddddddddbbccffff..
    fffffffffcfccccccccfffffffffffffffefeeeefeeeeeeeeeefcffefccccbdbdbbccccffffffc..
    fffffffffffffffccccfffffffffffffeeffeeeeeeeeeeeeeeeffffeefcccbdddbcffffffffffb..
    fffffffffffffffcccffffffffffffeeeefeeeefeeeeefeeeeeffffeeefccbddddcfffffffffc...
    ffffffffffffffffcffffccffffffeefeefffffe1eeeefefeeeffffeeefcccbbddcfffffffcc....
    .ccccccfffffffffffffcccfffffeeefeeeffee11eeeefefeeeffffeeeefccbbbdcffffccccb....
    ......bfffffffffffcccffffffefeefeeefeee11eeeffffeeefffffeeeefccbddccccccccc.....
    .......cffffffffffccccfffffeffffefeee1111eeeffffeeffeeffeeeffccbddccccccc.......
    ........fffffffcffcccfffffefeeeffeeee1111eeefffeeeffeeffefefffccbbccccccc.......
    ........cfffffffffffffffffefeeeeeeeeccceeee1fffeeffeddefeeeffcccccccccc.........
    ........cffffffffffffffffeeeeefeeffbcfffee11ffeeeffeeeefeefefccbccccccc.........
    ......bcffbfffffffffffffeefeeefeffecccccbeb1ffeefff111efeeffccbccccccc..........
    ......cffbffffffffffffffeeeeeeffefbb777cdb11eeeef111111ffefcccccccccb...........
    .....bffffffffffffffffcfeeeeeeefef111771111eeeef11beeb1ffeeccccccccb............
    ....bffffffffffffffffcdfefeeeeefef111111111eee1111bfc1fffeeccccccb..............
    ....fffffffffffffffffd1fefeeeeefffb1111111ff11111be771fffeecccccb...............
    .bcfffffffffffffffffc1dfeffeeeeeffb111111111111111bbbbffffefcbb.................
    dcfffffffffffffffffceddfeefeeeeefff1111111111111111111fcffefe...................
    cffffffffffffffffcceeedfeffeeefeefcf11111111111d111111ccffefe...................
    ffffffffffffffccceeeeeedeefeeeefeeef11111111111d111111cbbfeee...................
    ffffffffffffcbbfeeeeeeeefeefeeeefffb111111111111111111b..fffe................dd1
    fffffffffccbbbfeeeeeeeeefeeffeeeeffcb11111111111111111b..ffee..............ddd11
    fffffffcbbbbbbfeeeeeeeeeefeeffefeefd11111111111111111b...ffee.............1dd11d
    fffffcbbbbdbddfeeeeeeeeeeefefffffeeed1111111111111111b...feee.............dd1ddd
    ffffcbbbbdbddfeeeeefeeeeeffeefffffeeeed1111dddddd111bfeeeeeed.............11dddd
    fccbbbbbbdbddfeeeeeeefeefffeffffffffeefbbb1111111111bdeeeeed............b1dddddb
    cbbbbbbbdddddfeeeeefffeeefffffffffffffffbb11111111fefeeeeee........bbb.b1ddddddb
    bbbbbbbbcddddfeeeeeeeeeeeeeffffbbbbbbbdd1111111111eeeeeeee...bbcccccccb1ddddddb.
    bbbbbccccbdddfeeeeeeeeeeeedddeeffbdddd11111111111dedeeeeee...ccccccccd1dddddbb..
    ccccccccccbddfeeeeeeeeeeeeeeeeeefffdddd111111111dbddddebe...bccccccbdddbbbbb....
    cccccccccccdddffeeeffeeeeeeeeeeeffffdbbdd111111dbd1ddeed....ccccccbddbccc.......
    ccccccccccccbbbcfeeeeeeeeeedeeeeeefffbfffbdd11dbbd111dd....ccccfcbbccffffb......
    cccccccccccccccccfeeeeeeeeeeeeeeeeefbffffffeeeeffb........ccccfcbcffcfffccd.....
    ccccccccccccccccccfeeeeeeddeeeeeeeeefffffffeefffffcbbd...bccfeeccfffccfffcc.....
    ccccccccccccccccccfeeeeeddeeeeeeeffecffffffeefcffffcc.....beeefffffccccfffc.....
    cccccccccccccccccccfeeeeeeefffffeeffcfffffcccbbccffccc...bbeecfffffccccffffc....
    ..ccccccccccccccccccccfeeffffccfffffcfcfcfccbbbccffccccbebefccfffffcfccffffccd..
    ..............ccccccccccccccccfcfffcfffcffcbccbbcccccccccfffffffffcccccccccccb..
    ..............cccccccccccccccffffffcffffffcbb111111cccccbfffffffffffffcccfffcc..
    .............ccccccccccccccfffffcffcfffffcb111111111bccc.bbbbcfffffcffffffffffc.
    .............ccccccccccccccffffccccfffffcb11111111111ccc.....bfffffcccfffffffffc
    .............ccccccccccccffffffcccffffcbb111111111111bcc......bcffcccfffffffffff
    .............ccccccfccffffffffffccfffcbb11111111111111cccb......cfccffffffffffff
    .............bccccffffffffffcccccfffcbb111111111111111ccbcc......bbbccffffffffff
    ............bbcccfffffffffcccfcffffcbbb1111111111111111bccccb........bffffffffff
    .............bbccffffffccccccccfffcbbbb1111111111111111cbcccc........bcfffffffff
    ............bbbccffffccccccccccfcfcbbbbb111111111111111bbcccfc........cfffffffff
    ...........bbbcccccccccccccccccccfcccbbb111111111111111bccccffcb......cccfffffff
    ...........bbccccccccccccccccccccccccccbb111111111111111ccccffc......bccffffffff
    ...........ccccccccccccccccccccccccccccccbb1111111111111ccfffcb......bcccffffffc
    ...........cccccccccbcccccccccccccccccccccbbbbbb1111111cccccccc.....ccccbcfcfff.
    ...........ccccccccbbbccccccccccbccccccccccccbbbbbbbbbcccccfcccb....bcbbccccccc.
    ...........cccccccbddbbccccccccbbbccccccccccccccccbbbccccccccccb...ccccbcfccccc.
    ...........ccccccbd1dbcccccccccbddcccccccccccccccccbccccbcccccbbb..bbcbbfffcccf.
    ..........cccccccbd1dbccccccccbddddccccccccccccccccccccbbbcccccbbbbcbcccccccccf.
    ..........ccccccccddbcccccccccbddddbccccccccccccccbbbbbbbbccccccbcbbbccccccfccc.
    .........cccccccccbbbbccccccccdddd1dcccccccccccccbbbbbbbbcccccccccccbbbbcccffcc.
    .........cccccccbcbbcbcccccccbdddd1dcccccccccbcbbbbbbbbbbbcbccccbcccbbbbccccccc.
    .........cccccccbcbbbbcccccccbdddd11cccccccccbbbbbbbbbbbbbccbcccbbbccccccccbccc.
    ........ccccccccbbcbbccccccccbdddd11bccccccccbbbbbbbbbbbbbcccccbccccbbbcccbdbcc.
    .......bccccccbbbccbbccccccccbdddbbdbccccccccbbbbbbbbbbbbbbbbbccbcbbddddbdddbc..
    ......bccccccbbbbbcbbccccccccccbbbbbcccccccccbbbbbbbbbbbbbbbbbcbbcbdddddddddcb..
    .....dcccccbcbbbcbbdbccccccccccccbbbccccccccbbbbbbbbbbbbbbbbbcbbbcbdddddddddc...
    .....ccccccccbbcbcbdbbccccccccfffcccccccccccbbbbbbbbbbbbbbbbcbbbccddddddddddc...
    ....bccccccccccbbcbccbcccccccffffccfccccccccbbbbbbbbbbbbbbbbbbbbcbdddddddddbc...
    ...bccccccccccbdbbcccbcccccccffffccfccccccccbbbbbbbbbbbbbbbbbbbbcddddddddddbc...
    ..dccbccccccbbddcbccccbcccccfffffccfccccccccbbbbbbbbbbbbbbbbbbbccbdddddddddbb...
    .dcccbccccbbcbdbcbccccbcccccfffffcfccccccccbbbbbbbbbbbbbbbbbbbbbbcbddddddddbb...
    .cccbbcccbbbdbdbbbccccbcccccfffffffcccffcbccbbbbbbbbbbbbbbbbbbbbbbcbbddddddc....
    bccbddbbbbbd.bdcbbccccbccccffffffffccffccbbcbbbbbbbbbbbbbbbbbbbbbbbccddddddc....
    ccbddddbccd..bbbbbccccbbcccfffffffccccfccbbbbbbbbbbbbbbbbbbbbbbbbbbccddddddc....
    ccbbbbbccb...bcbcbccccbbccffffffffccccfccbbbbbbbbbbbbbbbbbbbbcbbbcccbddddddc....
    cbccbbcbb....dcbcdccccbbccffffffffcccfffcccbbbbbbbbbbbbbbbbbcbbcbbbddddddddb....
    cccbcccbd....dbccdbccbdcccffffffffffffcffccbbbbbbbbbbbbbbbbbcbdbbdddddddddc.....
    cbbcccbd.....bbccbdbbddcccfffffffffcccccffffccbbbbbbbbbbbbbbcddbbdddddddddc.....
    bccccbb......bbcccbdddbcccffffffffccccccffffffbbbbbbbbbbbbbcbdddbbddddddddc.....
    ccccbb......dbccccccbdccccffffffffcccccccffffcbbbbccbccbbbbcdddddbddddddddc.....
    cccbbb......bbcccbccbdcccccfffffffccccccccfffbbbbccdddbccccddd1ddbbdddddddc.....
    cccbb......dbccccbcccbcccccfffffffcccccccccfcbbbccdddddddddddd1ddbbdddddddc.....
    ccbb.......bbccccbccccccccccfffffccccccccccfccccffbddd111ddddd11dbbddddddcb.....
    ccb........bbccccbccccccccccfffffccccccccccfffffffcddd1111111111dbbddddddc......
    bbb.......dbcccccbbcccccccccfffffccccccccccfffffffcddd11111111111dbddddddc......
    .b........bbcccccdbcccccccccffffffccccccccccfffffcccdd11111111111ddddddddc......
    b.........bdcccccddccccccfcccfffffcccccccccccfffcbbcdd11111111111dddddddc.......
    b........dbdccccbbdbcccccfcccfffffcccccccccccfffcbbccd11111111111dddddddc.......
    .........bdddbcbdbbbcccccfcccfffffccccccccccccfffcbbbbd1111111111ddddddc........
    .........bdbbdddbccdcccccccfccfffffccccccccccccfcbccccb1111111111dddddc.........
    ........dbbccbdbcccbbccccccfccfffffcccccccccccccbcfccccd111111111ddddc..........
    ........dbcccbdccccbbcccccccfccffffccccccccccccbbcfccccbd1111111ddddb...........
    ........bbcccbbccccbbccccccccccffffcccccccccccddbffcccccd1111111dddc............
    `, SpriteKind.Player)
let yn = sprites.create(img`
    .....................eeeeeeeeeeeeeeeeeeeeeee....................
    ...................eeeeeeeeeeeeeeeeeeeeeeeeeeee.................
    ..................eeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    ................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...............
    ...............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    .............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    ............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..........
    ...........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.........
    ..........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee........
    ..........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.......
    ..........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.......
    .........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.......
    ..........e1eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......
    .........eeeeeeeeeeee1eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......
    ........eeeeeeeeeee111eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......
    ........eeeee11ee11111eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......
    ........eeeee1eee11e11eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.....
    ........eeeeeeee11111eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.....
    .......eeeeeeeeeee1e1ee1111ee1eeeeeeeeeeeeeeeeeeeeeeeeeeeee.....
    .......eeeeeeeeeee1e1ee1111ee111eeeeeeeeeeeeeeeeeeeeeeeeeee.....
    .......eeeeeeeeeeeee1ee1111ee1111eeeeee1eeeeeeeeeeeeeeeeeee.....
    ........eeeeeeeeeeeeee11111e11111eeeeee1eeeeeeeeeeeeeeeeeee.....
    ........eeeeeeeeeeeeeeeeeeeeeeeeeee111e1eeeeeeeeeeeeeeeeeee.....
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee....
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee....
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebeeeeeeeee....
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee....
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbeebbeeeee.....
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbebbbeeee......
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbeebbeeeee......
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebeebbebdbeeee.......
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbddbee.........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbeeebdd1dbee.........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbd1d1ddbb..........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebd1dd11111dd11.........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebd1111111111111.........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeed111111111111111........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeb1111111111111111........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeb1111111111111111........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebb111111111111111.........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedb11111111111111..........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedd11111111111111..........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeed1111111ddddd11...........
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeee11111111111111............
    .......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeee11111111111111............
    .......eeeeeeeeeeeeeeeeeeeeeeeeeefeeee11111111111111............
    .......eeeeeeeeefeeeeeeeeeefeeeeefceee1111111111111.............
    .......eeeeeeeeefeeeeeeeeeefeeeeffceee1111111111111.............
    .......eefeeeeeefeeeeeeeeeefceeeffceeed11111111111..............
    .......ecfceeeeefccfeeeeecefceecffceceddd111111111..............
    ......eecffeeeeefccffeeeeefffeefffeeeeeebdd1111111..............
    ......ecfffeeeeefccffeceeefffeefffeeceeeecebdd111...............
    ......ecffeeeeeffccfeceeeffffeeffeeeceeeecccebb.................
    ......ecffeeeeffccffeeeeefffeeeffeeeceeeccccccc.................
    .....becfeeeeeffccffeeeeffffeeeffeeeceeeccccccc.................
    .....becfeeeefffcfffeeecffffeeefffeeccceeceeeec.................
    .....befeeeeffffffffeefcfffceeefffeeccceeceeeee.................
    ....beefeeeefffcfffeeefcffeeeeeffceecccececeeec.................
    ....beefeeeffffcfffeefcffeeeeeeffceeccccceceeec.................
    ...bbecfeeefffecffeeefcfeeeeeeeffeeeeccececeeee.................
    ...bbecfeefffeeffeeefcfeeeeeeeeffceeeccccecceee.................
    ...becfeefffeecfeeeffceeebeeeeeefeeeeecccbcbdee.................
    ..bbeceefeeeecfeeeffffeebbeeeeeefeeeebbccccbdee.................
    bbbeceefffcccfeecffffeeedbeeeeebfeeeebdbccfceee.................
    bbeccefffccceecffffeeeebdeeeeeebeeeeed1dbcfffcc.................
    beccfffcccceefffffeceebddeeeeeebeeeeed11db888ff81...............
    ecfffcffffffffffcecceebdbeeeeeedeeeeeb111d88888881..............
    fffffcccfccffffceccebbdbeeeeeeedeeeeebd111b88888811.............
    ffffffffcceecffccbbbbddbeeeeeebdeeeeebd111db88888111............
    cffff8fffceeecffcbbbbdbeeeeeeebdeeeeebd1111d888881111...........
    fff888888ffeeeccfcbbdbbeeeeeeed1eeeeebdd1111b88888111...........
    f888888888888eeeccbbbeeeeeeeebbdbeeeebdd1111d888881111..........
    88888888888888eeeeeeeeeeeeeeebbdbeeeebdd11111b88881111..........
    8888888888888888eeeeeeeeeeeebdbdbeeeebddd1111d88881111..........
    88888888888888888eeeeeeeeeeedbbddeeeedddd11111b88881111.........
    8888888888888888888ceeccceeddbdddeeeedd1d11111db8881111.........
    88888888888888888888fffccbd1dbdddeeeebd1d111111b88811111........
    88888888888888888888fffcd111dddddeeeedddd111111db8811111.1......
    888888888888888888888ffcb11ddddddeeeedd1dd111111b8881111.1......
    8888888888888888888888fccddddddddeeeedd1dd111111b8881111.1......
    88888888888888888888888cccbd1ddddeeeedd11bbd1111b8881111.1......
    888888888888888888888888cccd1ddddeeeedd1dbbbdddbb888111111......
    8888888888888888888888888cccdddddeeeedd1dbbbbbbbbb88111111......
    `, SpriteKind.Player)
controller.moveSprite(yn)
yn.setPosition(38, 43)
lisa.setPosition(122, 57)
Script()
